apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: pod-network-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-network-operator
  namespace: pod-network-operator
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: pod-network-operator-sa
      nodeSelector:
        cnf-telco: "true"   
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: quay.io/opdev/pod-network-operator:0.0.1
        imagePullPolicy: Always
        name: pod-network-operator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          privileged: true          
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 500m
            memory: 200Mi
        volumeMounts:
          - mountPath: /tmp/proc
            name: proc
          - mountPath: /var/run/crio/crio.sock
            name: crio-sock
      volumes:
      - name: proc
        hostPath:
          # Mounting the proc file system to get process namespaces
          path: /proc
          type: Directory
      - name: crio-sock
        hostPath:
          # Mounting the proc file system to get process namespaces
          path: /var/run/crio/crio.sock
          type: Socket            
      terminationGracePeriodSeconds: 10
