# permissions for end users to edit additionalnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: additionalnetworks-editor-role
rules:
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - additionalnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - additionalnetworks/status
  verbs:
  - get
