# permissions for end users to edit bridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bridge-editor-role
rules:
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - bridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - bridges/status
  verbs:
  - get
