# permissions for end users to edit linktemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linktemplate-editor-role
rules:
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - linktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - linktemplates/status
  verbs:
  - get
