# permissions for end users to edit primarynetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: primarynetwork-editor-role
rules:
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - primarynetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - primarynetworks/status
  verbs:
  - get
