# permissions for end users to view primarynetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: primarynetwork-viewer-role
rules:
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - primarynetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - primarynetworks/status
  verbs:
  - get
