
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - additionalnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - additionalnetworks/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - additionalnetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - bridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - bridges/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - bridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - primarynetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - primarynetworks/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - primarynetworks/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: cnf-test
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
