
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - bridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - bridges/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - bridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - linktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - linktemplates/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - linktemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs/status
  verbs:
  - get
  - patch
  - update
