
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - podnetworkconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - veths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - veths/finalizers
  verbs:
  - update
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - veths/status
  verbs:
  - get
  - patch
  - update
