# permissions for end users to edit veths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: veth-editor-role
rules:
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - veths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podnetwork.opdev.io
  resources:
  - veths/status
  verbs:
  - get
