apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnf-example-a
  namespace: cnf-test
  labels:
    podNetworkConfig: podnetwork-sample-a
spec:
  selector:
    matchLabels:
      podNetworkConfig: podnetwork-sample-a
  replicas: 2
  template:
    metadata:
      name: cnf-example-a
      namespace: cnf-test
      labels:
        podNetworkConfig: podnetwork-sample-a
    spec:
      serviceAccountName: default
      containers:
      - command:
        - /bin/bash 
        - -c 
        - --
        args:
        - "while true; do sleep 30; done;"
        image: "nicolaka/netshoot:latest"
        imagePullPolicy: Always
        name: cnf-example
