## Append samples you want in your CSV to this file as resources ##
resources:
- podnetworking_v1alpha1_podnetworkconfig.yaml
- podnetworking_v1alpha1_veth.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
