apiVersion: podnetwork.opdev.io/v1alpha1
kind: PodNetworkConfig
metadata:
  name: podnetwork-sample-a
  namespace: cnf-telco
spec:
  Name: podnetwork-sample-a
  additionalNetworks:
    - networkName: pno
      networkDescription: "Service to service encrypted communication."
      linkType: veth
      master: pnobr0
      cidr: "192.168.100.0/24"